#!/bin/sh

if test -d src/social_wallet_api; then
	docker build -f docker/Dockerfile \
		   -t dyne/social-wallet-api:latest \
		   --force-rm .
else
	echo "Launch from base source directiory. Usage:"
	echo "./docker/build"
fi
