#!/bin/sh

VERSION=${version:-latest}

## run with --no-cache as argument
## it is passed along with other options
if test -d src/social_wallet_api; then
	docker build $* -f docker/Dockerfile \
		   -t dyne/social-wallet-api:$VERSION \
		   --force-rm .
else
	echo "Launch from base source directiory. Usage:"
	echo "./docker/build"
fi
